name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONFIGURATION: Release

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          external_repository: mono/CppSharp
          publish_dir: ./build
